
sonar.exclusions=src/main/java/com/frontleaves/scheduling/configs/apps/**,src/main/java/com/frontleaves/scheduling/configs/filters/**,src/main/java/com/frontleaves/scheduling/controllers/InitController.java
