spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://172.16.11.3:3306/class-scheduling?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8"
    username: "class-scheduling"
    password: "123456"
logging:
  level:
    com.frontleaves: info
    com.frontleaves.scheduling.mappers: info
xutil:
  mail:
    default-encoding: "utf-8"
    host: "smtp.qiye.aliyun.com"
    username: "debug@x-lf.cn"
    password: "QAZwsx123"
    nickname: "ClassScheduling"
    port: 25
