server:
  port: 8888
spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  file:
    path: "./.logs"
  level:
    root: error
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
