server:
  port: 8888
spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
logging:
  file:
    path: "./.logs"
  level:
    root: error
