spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/class-scheduling-system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8"
    username: "class-scheduling-system"
    password: "123456"
logging:
  level:
    com.frontleaves: debug
    com.frontleaves.scheduling.mappers: info
    com.xlf: debug
xutil:
  mail:
    default-encoding: "utf-8"
    host: "smtp.qiye.aliyun.com"
    username: ""
    password: ""
    nickname: "ClassScheduling"
    port: 25
