# 可以自己编辑操作使用（将 CLI 下载后放在当前文件夹下即可使用）

[database]
# 数据库主机地址
host = "localhost"
# 数据库端口
port = 3306
# 数据库名称
name = "class-scheduling-system"
# 数据库用户名
user = "class-scheduling-system"
# 数据库密码
password = "123456"
